### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by phd0066** [web3bothub/gradient-bot#11]
Failed to get proxy IP info: WebDriverError: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED

**Comment by phd0066** [comment]
at Object.throwDecodedError (/app/node_modules/selenium-webdriver/lib/error.js:521:15)
2024-10-30 12:46:45 0|gradient-0  |     at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:514:13)
2024-10-30 12:46:45 0|gradient-0  |     at Executor.execute (/app/node_modules/selenium-webdriver/lib/http.js:446:28)
2024-10-30 12:46:45 0|gradient-0  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-10-30 12:46:45 0|gradient-0  |     at async Driver.execute (/app/node_modules/selenium-webdriver/lib/webdriver.js:744:17)
2024-10-30 12:46:45 0|gradient-0  |     at async getProxyIpInfo (/app/app.js:143:5)
2024-10-30 12:46:45 0|gradient-0  |     at async /app/app.js:180:7 {
2024-10-30 12:46:45 0|gradient-0  |   remoteStacktrace: '#0 0x562234c6fd93 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#1 0x562234953337 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#2 0x56223494b193 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#3 0x56223493b161 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#4 0x56223493c5cb <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#5 0x56223493b414 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#6 0x56223493a5e5 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#7 0x56223493a557 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#8 0x562234938c1a <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#9 0x5622349391ca <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#10 0x562234955b6e <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#11 0x5622349e0d45 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#12 0x5622349c1442 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#13 0x5622349e012d <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#14 0x5622349c11e3 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#15 0x562234991135 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#16 0x56223499213e <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#17 0x562234c33e4b <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#18 0x562234c37dfa <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#19 0x562234c206d5 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#20 0x562234c38a6f <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#21 0x562234c0469f <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#22 0x562234c5d098 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#23 0x562234c5d262 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#24 0x562234c6ef34 <unknown>\n' +
2024-10-30 12:46:45 0|gradient-0  |     '#25 0x7f0ad99dc144 <unknown>\n'
2024-10-30 12:46:45 0|gradient-0  | }
