### ISSUE TITLE
docker logs ID打印出来的内容不符合

### ISSUE THREAD

**Issue by 631202349** [web3bothub/gradient-bot#12]
日志内容如下，没有gradient相关信息：
PS D:\web3\gradient-bot-main\proxy> docker restart 806ff8aa699c
806ff8aa699c
PS D:\web3\gradient-bot-main\proxy> docker logs 806ff8aa699c
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readFileSync (node:fs:448:20)
    at Object.<anonymous> (/app/start.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}

Node.js v20.18.0

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__

                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/

                        -------------

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2024-10-30T05:34:07: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2024-10-30T05:34:07: PM2 log: Time                 : Wed Oct 30 2024 05:34:07 GMT+0000 (Coordinated Universal Time)
PM2        | 2024-10-30T05:34:07: PM2 log: PM2 version          : 5.4.2
PM2        | 2024-10-30T05:34:07: PM2 log: Node.js version      : 20.18.0
PM2        | 2024-10-30T05:34:07: PM2 log: Current arch         : x64
PM2        | 2024-10-30T05:34:07: PM2 log: PM2 home             : /root/.pm2
PM2        | 2024-10-30T05:34:07: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2024-10-30T05:34:07: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2024-10-30T05:34:07: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2024-10-30T05:34:07: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2024-10-30T05:34:07: PM2 log: Worker Interval      : 30000
PM2        | 2024-10-30T05:34:07: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2024-10-30T05:34:07: PM2 log: Concurrent actions   : 2
PM2        | 2024-10-30T05:34:07: PM2 log: SIGTERM timeout      : 1600
PM2        | 2024-10-30T05:34:07: PM2 log: ===============================================================================

node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readFileSync (node:fs:448:20)
    at Object.<anonymous> (/app/start.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}

Node.js v20.18.0
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2024-10-30T05:36:00: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2024-10-30T05:36:00: PM2 log: Time                 : Wed Oct 30 2024 05:36:00 GMT+0000 (Coordinated Universal Time)
PM2        | 2024-10-30T05:36:00: PM2 log: PM2 version          : 5.4.2
PM2        | 2024-10-30T05:36:00: PM2 log: Node.js version      : 20.18.0
PM2        | 2024-10-30T05:36:00: PM2 log: Current arch         : x64
PM2        | 2024-10-30T05:36:00: PM2 log: PM2 home             : /root/.pm2
PM2        | 2024-10-30T05:36:00: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2024-10-30T05:36:00: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2024-10-30T05:36:00: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2024-10-30T05:36:00: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2024-10-30T05:36:00: PM2 log: Worker Interval      : 30000
PM2        | 2024-10-30T05:36:00: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2024-10-30T05:36:00: PM2 log: Concurrent actions   : 2
PM2        | 2024-10-30T05:36:00: PM2 log: SIGTERM timeout      : 1600
PM2        | 2024-10-30T05:36:00: PM2 log: ===============================================================================

**Comment by 631202349** [comment]
这是我的创建容器的命令：docker run -d   --name GradientBot   -e APP_USER=打码  -e APP_PASS=打码    -v ./proxies.txt:/app/proxies.txt  overtrue/gradient-bot，很奇怪的是，我看容器内的proxies.txt是一个目录，目录内是空的

**Comment by 631202349** [comment]
PS D:\web3\gradient-bot-main\proxy> docker exec -i -t 806ff8aa699c47ac5ff56d8d78361fde11849d8aee368b8782a42e9aee3f80a2 /bin/bash
root@806ff8aa699c:/app# ls
Dockerfile  README.md  app.crx  app.js  entrypoint.sh  node_modules  package-lock.json  package.json  proxies.txt  start.js  test.js
root@806ff8aa699c:/app# cat proxies.txt/
cat: proxies.txt/: Is a directory
root@806ff8aa699c:/app#

**Comment by 631202349** [comment]
so where is my Proxy info in?

**Comment by 631202349** [comment]
![image](https://github.com/user-attachments/assets/0b8e4f1f-fcc7-4f98-9fc1-72147ea325a1)
我映射的也是txt文件，不可能出错

**Comment by 631202349** [comment]
windows使用相对路径会有问题，改为全路径即可
