### ISSUE TITLE
error sessionNotCreated

### ISSUE THREAD

**Issue by luqmanfajar** [web3bothub/gradient-bot#15]
Error occurred: SessionNotCreatedError: session not created: DevToolsActivePort file doesn't exist
4|gradient-4  |     at Object.throwDecodedError (/app/node_modules/selenium-webdriver/lib/error.js:521:15)
4|gradient-4  |     at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:514:13)
4|gradient-4  |     at Executor.execute (/app/node_modules/selenium-webdriver/lib/http.js:446:28)
4|gradient-4  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

**Comment by luqmanfajar** [comment]
it turns out need ' ' on password
