### ISSUE TITLE
Session not created

### ISSUE THREAD

**Issue by MHendriF** [web3bothub/gradient-bot#32]
![image](https://github.com/user-attachments/assets/7652c93e-6963-409d-a737-77d70765342b)

what does mean of this error?

**Comment by Lukey372** [comment]
Try restarting your container a few times (worked for me)

**Comment by iamspa** [comment]
10|gradient-9   |     at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:514:13)
10|gradient-9   |     at Executor.execute (/app/node_modules/selenium-webdriver/lib/http.js:446:28)
10|gradient-9   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10|gradient-9   |     at async Driver.execute (/app/node_modules/selenium-webdriver/lib/webdriver.js:744:17)
10|gradient-9   |     at async getProxyIpInfo (/app/app.js:177:5)
10|gradient-9   |     at async /app/app.js:215:9 {
10|gradient-9   |   remoteStacktrace: '#0 0x5557ff0216da <unknown>\n' +
10|gradient-9   |     '#1 0x5557feb35f80 <unknown>\n' +
10|gradient-9   |     '#2 0x5557feb2e181 <unknown>\n' +
10|gradient-9   |     '#3 0x5557feb1e8b9 <unknown>\n' +
10|gradient-9   |     '#4 0x5557feb205ea <unknown>\n' +
10|gradient-9   |     '#6 0x5557feb1e3df <unknown>\n' +
10|gradient-9   |     '#7 0x5557feb1e2d2 <unknown>\n' +
10|gradient-9   |     '#9 0x5557feb1c99a <unknown>\n' +
10|gradient-9   |     '#10 0x5557feb38879 <unknown>\n' +
10|gradient-9   |     '#12 0x5557feba6bb2 <unknown>\n' +
10|gradient-9   |     '#13 0x5557febc569d <unknown>\n' +
10|gradient-9   |     '#14 0x5557feba6953 <unknown>\n' +
10|gradient-9   |     '#15 0x5557feb7572e <unknown>\n' +
10|gradient-9   |     '#16 0x5557feb7679e <unknown>\n' +
10|gradient-9   |     '#17 0x5557fefecf1b <unknown>\n' +
10|gradient-9   |     '#18 0x5557feff0eb8 <unknown>\n' +
10|gradient-9   |     '#19 0x5557fefda42c <unknown>\n' +
10|gradient-9   |     '#20 0x5557feff1a37 <unknown>\n' +
10|gradient-9   |     '#21 0x5557fefbefef <unknown>\n' +
10|gradient-9   |     '#22 0x5557ff00fad8 <unknown>\n' +
10|gradient-9   |     '#23 0x5557ff00fca0 <unknown>\n' +
10|gradient-9   |     '#24 0x5557ff020556 <unknown>\n' +
10|gradient-9   |     '#25 0x7f3d10f9b144 <unknown>\n'

still error 
already restart the docker multiple times
