### ISSUE TITLE
不能启动驱动

### ISSUE THREAD

**Issue by ljj0522** [Web3BotHub/gradient-bot#7]
Error occurred: Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /root/gradient-bot/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,chrome,--language-binding,javascript,--output,json,--proxy,http://127.0.0.1:40243: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)
    at getBinaryPaths (/root/gradient-bot/node_modules/selenium-webdriver/common/driverFinder.js:38:11)
    at thenableWebDriverProxy.createSession (/root/gradient-bot/node_modules/selenium-webdriver/chromium.js:627:45)
    at thenableWebDriverProxy.createSession (/root/gradient-bot/node_modules/selenium-webdriver/chrome.js:219:42)
    at createDriver (/root/gradient-bot/node_modules/selenium-webdriver/index.js:153:33)
    at Builder.build (/root/gradient-bot/node_modules/selenium-webdriver/index.js:674:16)
    at /root/gradient-bot/app.js:174:8
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /root/gradient-bot/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,chrome,--language-binding,javascript,--output,json,--proxy,http://127.0.0.1:40243: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)
    at getBinaryPaths (/root/gradient-bot/node_modules/selenium-webdriver/common/driverFinder.js:38:11)
    at thenableWebDriverProxy.createSession (/root/gradient-bot/node_modules/selenium-webdriver/chromium.js:627:45)
    at thenableWebDriverProxy.createSession (/root/gradient-bot/node_modules/selenium-webdriver/chrome.js:219:42)
    at createDriver (/root/gradient-bot/node_modules/selenium-webdriver/index.js:153:33)
    at Builder.build (/root/gradient-bot/node_modules/selenium-webdriver/index.js:674:16)
    at /root/gradient-bot/app.js:174:8
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

**Comment by overtrue** [comment]
代理地址不可用或者配置写法错误，验证代理地址先

**Comment by ljj0522** [comment]
> 代理地址不可用或者配置写法错误，验证代理地址先

0|gradient-0  | Error occurred: TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Copy Referral Link")])
0|gradient-0  | Wait timed out after 30025ms
0|gradient-0  |     at /app/node_modules/selenium-webdriver/lib/webdriver.js:923:22
0|gradient-0  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|gradient-0  |   remoteStacktrace: ''
0|gradient-0  | }
修改了await后的等待时间为30000ms，但是不生效
